import { Plus, WandSparkles } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { bulkApplyRulesAction, deleteRuleAction, toggleRuleAction } from "@/features/categorization/actions";
import { DeleteRuleButton } from "@/features/categorization/delete-rule-button";
import { getCategorizationRepository } from "@/features/categorization/server-repository";

export const dynamic = "force-dynamic";
const statuses: Record<string, string> = { created: "Rule created.", updated: "Rule updated.", deleted: "Rule deleted.", enabled: "Rule enabled.", disabled: "Rule disabled.", "action-error": "The requested rule action failed." };
export default async function RulesPage({ searchParams }: { searchParams: Promise<{ status?: string; count?: string }> }) {
  const { status, count } = await searchParams; const rules = getCategorizationRepository().list(); const message = status === "applied" ? `${Number(count ?? 0)} uncategorized transaction${Number(count ?? 0) === 1 ? "" : "s"} updated.` : status ? statuses[status] : undefined;
  return <section className="mx-auto max-w-5xl space-y-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-primary">Categorization</p><h1 className="text-3xl font-semibold tracking-tight">Rules</h1><p className="mt-2 text-sm text-muted-foreground">The first enabled matching rule assigns its category and optional transaction type.</p></div><Button asChild><Link href="/rules/new"><Plus className="mr-2 h-4 w-4" />Add rule</Link></Button></div>
    {message && <div className={`rounded-md border p-3 text-sm ${status === "action-error" ? "border-red-200 bg-red-50 text-red-800" : "border-emerald-200 bg-emerald-50 text-emerald-900"}`} role="status">{message}</div>}
    <div className="flex flex-col items-start justify-between gap-3 rounded-xl border bg-card p-4 sm:flex-row sm:items-center"><div><p className="font-medium">Apply rules to uncategorized transactions</p><p className="text-sm text-muted-foreground">Only active transactions without a category will change.</p></div><form action={bulkApplyRulesAction}><Button type="submit" variant="outline"><WandSparkles className="mr-2 h-4 w-4" />Apply enabled rules</Button></form></div>
    {rules.length ? <div className="space-y-3">{rules.map((rule) => <article className={`rounded-xl border bg-card p-5 shadow-sm ${rule.isEnabled ? "" : "opacity-60"}`} key={rule.id}><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold">{rule.name}</h2><span className="rounded-full bg-muted px-2 py-0.5 text-xs">Priority {rule.priority}</span>{!rule.isEnabled && <span className="rounded-full bg-muted px-2 py-0.5 text-xs">Disabled</span>}</div><p className="mt-2 text-sm"><span className="text-muted-foreground">{rule.matchField.replace("_", " ")} · {rule.matchType.replace("_", " ")} · </span><code className="rounded bg-muted px-1 py-0.5">{rule.pattern}</code></p><p className="mt-1 text-sm text-muted-foreground">Assign {rule.categoryName}{rule.transactionType ? ` and ${rule.transactionType}` : ""}</p></div><div className="flex flex-wrap gap-2"><Button asChild size="sm" variant="outline"><Link href={`/rules/${rule.id}/edit`}>Edit</Link></Button><form action={toggleRuleAction}><input name="id" type="hidden" value={rule.id} /><input name="enabled" type="hidden" value={String(!rule.isEnabled)} /><Button size="sm" type="submit" variant="outline">{rule.isEnabled ? "Disable" : "Enable"}</Button></form><form action={deleteRuleAction}><input name="id" type="hidden" value={rule.id} /><DeleteRuleButton name={rule.name} /></form></div></div></article>)}</div>
      : <div className="rounded-xl border border-dashed bg-card p-10 text-center"><WandSparkles className="mx-auto h-8 w-8 text-muted-foreground" /><h2 className="mt-3 font-semibold">No categorization rules yet</h2><p className="mt-2 text-sm text-muted-foreground">Create a rule and preview which transactions it matches.</p><Button asChild className="mt-5"><Link href="/rules/new">Create first rule</Link></Button></div>}
  </section>;
}
