import { Plus, Search } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { formatCurrency } from "@/features/accounts/money";
import { deleteTransactionAction } from "@/features/transactions/actions";
import { DeleteTransactionButton } from "@/features/transactions/delete-button";
import { transactionTypeLabels, type TransactionFilters } from "@/features/transactions/model";
import { getTransactionRepository } from "@/features/transactions/server-repository";
import { isTransactionType } from "@/features/transactions/validation";
import { localMonthString } from "@/lib/dates";

export const dynamic = "force-dynamic";
type Params = { search?: string; account?: string; category?: string; type?: string; from?: string; to?: string; page?: string; month?: string; status?: string };
const statuses: Record<string, string> = { created: "Transaction created.", updated: "Transaction updated.", deleted: "Transaction deleted.", "delete-error": "The transaction could not be deleted." };
function validDate(value?: string) { if (!value || !/^\d{4}-\d{2}-\d{2}$/.test(value)) return undefined; const [year, month, day] = value.split("-").map(Number); const date = new Date(Date.UTC(year, month - 1, day)); return date.getUTCFullYear() === year && date.getUTCMonth() === month - 1 && date.getUTCDate() === day ? value : undefined; }
function validMonth(value?: string) { return value && /^\d{4}-(0[1-9]|1[0-2])$/.test(value) ? value : localMonthString(); }
function pageHref(params: Params, page: number) { const query = new URLSearchParams(); for (const [key, value] of Object.entries(params)) if (value && key !== "status" && key !== "page") query.set(key, value); query.set("page", String(page)); return `/transactions?${query}`; }

export default async function TransactionsPage({ searchParams }: { searchParams: Promise<Params> }) {
  const params = await searchParams; const repository = getTransactionRepository(); const options = repository.listOptions();
  const requestedPage = Number.parseInt(params.page ?? "1", 10); const filters: TransactionFilters = { search: params.search?.trim() || undefined, accountId: params.account || undefined, categoryId: params.category || undefined,
    transactionType: isTransactionType(params.type) ? params.type : undefined, dateFrom: validDate(params.from), dateTo: validDate(params.to), page: Number.isFinite(requestedPage) && requestedPage > 0 ? requestedPage : 1, pageSize: 20 };
  const result = repository.list(filters); const month = validMonth(params.month); const totals = repository.monthlyTotals(month);
  return <section className="mx-auto max-w-6xl space-y-7">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-primary">Transactions</p><h1 className="text-3xl font-semibold tracking-tight">Money in and out</h1><p className="mt-2 text-sm text-muted-foreground">Search, categorize, and review manual transactions.</p></div><Button asChild><Link href="/transactions/new"><Plus className="mr-2 h-4 w-4" />Add transaction</Link></Button></div>
    {params.status && statuses[params.status] && <div className={`rounded-md border p-3 text-sm ${params.status === "delete-error" ? "border-red-200 bg-red-50 text-red-800" : "border-emerald-200 bg-emerald-50 text-emerald-900"}`} role="status">{statuses[params.status]}</div>}
    <form className="grid gap-3 rounded-xl border bg-card p-4 sm:grid-cols-2 lg:grid-cols-4" method="get">
      <label className="relative sm:col-span-2"><span className="sr-only">Search transactions</span><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" /><input className="h-10 w-full rounded-md border bg-background pl-9 pr-3 text-sm" defaultValue={params.search} name="search" placeholder="Search description or merchant" /></label>
      <label><span className="sr-only">Account</span><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" defaultValue={params.account ?? ""} name="account"><option value="">All accounts</option>{options.accounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select></label>
      <label><span className="sr-only">Category</span><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" defaultValue={params.category ?? ""} name="category"><option value="">All categories</option><option value="uncategorized">Uncategorized</option>{options.categories.filter((category) => category.name !== "Uncategorized").map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label>
      <label><span className="sr-only">Transaction type</span><select className="h-10 w-full rounded-md border bg-background px-3 text-sm" defaultValue={params.type ?? ""} name="type"><option value="">All types</option>{Object.entries(transactionTypeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>
      <label className="flex items-center gap-2 text-sm"><span>From</span><input className="h-10 min-w-0 flex-1 rounded-md border bg-background px-2" defaultValue={params.from} name="from" type="date" /></label>
      <label className="flex items-center gap-2 text-sm"><span>To</span><input className="h-10 min-w-0 flex-1 rounded-md border bg-background px-2" defaultValue={params.to} name="to" type="date" /></label>
      <label className="flex items-center gap-2 text-sm"><span>Totals</span><input className="h-10 min-w-0 flex-1 rounded-md border bg-background px-2" defaultValue={month} name="month" type="month" /></label>
      <div className="flex gap-2 lg:col-span-4"><Button type="submit">Apply filters</Button><Button asChild variant="outline"><Link href="/transactions">Clear</Link></Button></div>
    </form>
    <div className="grid gap-4 sm:grid-cols-3"><div className="rounded-xl border bg-card p-5"><p className="text-sm text-muted-foreground">Income · {month}</p><p className="mt-2 text-2xl font-semibold tabular-nums text-emerald-700">{formatCurrency(totals.incomeCents)}</p></div><div className="rounded-xl border bg-card p-5"><p className="text-sm text-muted-foreground">Expenses · {month}</p><p className="mt-2 text-2xl font-semibold tabular-nums">{formatCurrency(totals.expenseCents)}</p></div><div className="rounded-xl border bg-card p-5"><p className="text-sm text-muted-foreground">Savings · {month}</p><p className={`mt-2 text-2xl font-semibold tabular-nums ${totals.savingsCents >= 0 ? "text-emerald-700" : "text-red-700"}`}>{formatCurrency(totals.savingsCents)}</p></div></div>
    {result.items.length ? <div className="space-y-3">{result.items.map((transaction) => <article className="grid gap-3 rounded-xl border bg-card p-4 shadow-sm sm:grid-cols-[7rem_1fr_auto] sm:items-center" key={transaction.id}><div><p className="text-sm font-medium">{transaction.date}</p><p className="text-xs text-muted-foreground">{transaction.accountName}</p></div><div><h2 className="font-medium">{transaction.description}</h2><p className="mt-1 text-sm text-muted-foreground">{transaction.merchant ? `${transaction.merchant} · ` : ""}{transaction.categoryName ?? "Uncategorized"} · {transactionTypeLabels[transaction.transactionType]}</p>{transaction.notes && <p className="mt-1 line-clamp-1 text-xs text-muted-foreground">{transaction.notes}</p>}</div><div className="flex items-center justify-between gap-3 sm:justify-end"><p className={`font-semibold tabular-nums ${transaction.amountCents > 0 ? "text-emerald-700" : ""}`}>{formatCurrency(transaction.amountCents)}</p><Button asChild size="sm" variant="outline"><Link href={`/transactions/${transaction.id}/edit`}>Edit</Link></Button><form action={deleteTransactionAction}><input name="id" type="hidden" value={transaction.id} /><DeleteTransactionButton /></form></div></article>)}</div>
      : <div className="rounded-xl border border-dashed bg-card p-10 text-center"><h2 className="font-semibold">No matching transactions</h2><p className="mt-2 text-sm text-muted-foreground">Add a transaction or clear the filters to see results.</p>{options.accounts.length ? <Button asChild className="mt-5"><Link href="/transactions/new">Add transaction</Link></Button> : <Button asChild className="mt-5"><Link href="/accounts/new">Add an account first</Link></Button>}</div>}
    <div className="flex items-center justify-between text-sm"><p className="text-muted-foreground">{result.totalCount} transaction{result.totalCount === 1 ? "" : "s"} · Page {result.page} of {result.totalPages}</p><div className="flex gap-2"><Button asChild={result.page > 1} disabled={result.page <= 1} size="sm" variant="outline">{result.page > 1 ? <Link href={pageHref(params, result.page - 1)}>Previous</Link> : <span>Previous</span>}</Button><Button asChild={result.page < result.totalPages} disabled={result.page >= result.totalPages} size="sm" variant="outline">{result.page < result.totalPages ? <Link href={pageHref(params, result.page + 1)}>Next</Link> : <span>Next</span>}</Button></div></div>
  </section>;
}
