import { Plus } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { AccountTypeIcon } from "@/features/accounts/account-type-icon";
import { formatCurrency } from "@/features/accounts/money";
import { deleteTransactionAction, updateTransactionAccountBalanceAction, updateTransactionCategoryAction, updateTransactionTypeAction } from "@/features/transactions/actions";
import { DeleteTransactionButton } from "@/features/transactions/delete-button";
import { InlineCategorySelect } from "@/features/transactions/inline-category-select";
import { InlineTransactionControls } from "@/features/transactions/inline-transaction-controls";
import { transactionDateSorts, type TransactionFilters } from "@/features/transactions/model";
import { getTransactionRepository } from "@/features/transactions/server-repository";
import { TransactionFilters as TransactionFiltersPanel } from "@/features/transactions/transaction-filters";
import { isAccountBalanceTreatment, isAmountComparison, isTransactionType, parseTransactionFilterAmount } from "@/features/transactions/validation";
import { localMonthString, transactionDateRangePresets } from "@/lib/dates";
import { cn } from "@/lib/utils";

export const dynamic = "force-dynamic";
type Params = { search?: string; account?: string; category?: string; type?: string; accountBalance?: string; from?: string; to?: string; amountComparison?: string; amount?: string; sort?: string; page?: string; month?: string; status?: string; suggest?: string };
const statuses: Record<string, string> = { created: "Transaction created.", updated: "Transaction updated.", deleted: "Transaction deleted.", "delete-error": "The transaction could not be deleted." };
function validDate(value?: string) { if (!value || !/^\d{4}-\d{2}-\d{2}$/.test(value)) return undefined; const [year, month, day] = value.split("-").map(Number); const date = new Date(Date.UTC(year, month - 1, day)); return date.getUTCFullYear() === year && date.getUTCMonth() === month - 1 && date.getUTCDate() === day ? value : undefined; }
function validMonth(value?: string) { return value && /^\d{4}-(0[1-9]|1[0-2])$/.test(value) ? value : localMonthString(); }
function truncateMerchant(value: string) { return value.length > 20 ? `${value.slice(0, 19)}…` : value; }
function pageHref(params: Params, page: number) { const query = new URLSearchParams(); for (const [key, value] of Object.entries(params)) if (value && key !== "status" && key !== "page") query.set(key, value); query.set("page", String(page)); return `/transactions?${query}`; }
function returnQuery(params: Params) { const query = new URLSearchParams(); for (const [key, value] of Object.entries(params)) if (value && key !== "status" && key !== "suggest") query.set(key, value); return query.toString(); }

export default async function TransactionsPage({ searchParams }: { searchParams: Promise<Params> }) {
  const params = await searchParams; const repository = getTransactionRepository(); const options = repository.listOptions();
  const suggestedTransaction = params.suggest ? repository.findById(params.suggest) : null;
  const suggestionQuery = suggestedTransaction?.categoryId ? new URLSearchParams({ name: `Categorize ${suggestedTransaction.description}`.slice(0, 100), matchField: "normalized_description", matchType: "exact", pattern: suggestedTransaction.normalizedDescription, categoryId: suggestedTransaction.categoryId, transactionType: suggestedTransaction.transactionType, priority: "100" }) : null;
  const requestedPage = Number.parseInt(params.page ?? "1", 10);
  const amountCents = parseTransactionFilterAmount(params.amount);
  const dateSort = transactionDateSorts.find((sort) => sort === params.sort) ?? "newest";
  const amountFilterError = params.amount?.trim() && amountCents === undefined ? "Enter a valid amount with at most 2 decimal places." : null;
  const filters: TransactionFilters = { search: params.search?.trim() || undefined, accountId: params.account || undefined, categoryId: params.category || undefined,
    transactionType: isTransactionType(params.type) ? params.type : undefined, flow: params.type === "spending" || params.type === "actual" ? params.type : undefined,
    accountBalanceTreatment: isAccountBalanceTreatment(params.accountBalance) ? params.accountBalance : undefined,
    dateFrom: validDate(params.from), dateTo: validDate(params.to), amountComparison: isAmountComparison(params.amountComparison) ? params.amountComparison : undefined,
    amountCents, dateSort, page: Number.isFinite(requestedPage) && requestedPage > 0 ? requestedPage : 1, pageSize: 20 };
  const result = repository.list(filters); const month = validMonth(params.month); const totals = repository.monthlyTotals(month);
  const datePresets = transactionDateRangePresets();
  return <section className="mx-auto max-w-6xl space-y-7">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-primary">Transactions</p><h1 className="text-3xl font-semibold tracking-tight">Money in and out</h1><p className="mt-2 text-sm text-muted-foreground">Search, categorize, and review manual transactions.</p></div><Button asChild><Link href="/transactions/new"><Plus className="mr-2 h-4 w-4" />Add transaction</Link></Button></div>
    {params.status && statuses[params.status] && <div className={`rounded-md border p-3 text-sm ${params.status === "delete-error" ? "border-red-200 bg-red-50 text-red-800" : "border-emerald-200 bg-emerald-50 text-emerald-900"}`} role="status">{statuses[params.status]}</div>}
    {suggestionQuery && <div className="flex flex-col items-start justify-between gap-3 rounded-md border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-950 sm:flex-row sm:items-center"><span>Apply this categorization automatically to matching transactions?</span><Button asChild size="sm" variant="outline"><Link href={`/rules/new?${suggestionQuery}`}>Create rule</Link></Button></div>}
    <TransactionFiltersPanel accounts={options.accounts} amountFilterError={amountFilterError} categories={options.categories} datePresets={datePresets} dateSort={dateSort} month={month} params={params} />
    <div className="grid gap-4 sm:grid-cols-3"><div className="rounded-xl border bg-card p-5"><p className="text-sm text-muted-foreground">Income · {month}</p><p className="mt-2 text-2xl font-semibold tabular-nums text-emerald-700">{formatCurrency(totals.incomeCents)}</p></div><div className="rounded-xl border bg-card p-5"><p className="text-sm text-muted-foreground">Expenses · {month}</p><p className="mt-2 text-2xl font-semibold tabular-nums">{formatCurrency(totals.expenseCents)}</p></div><div className="rounded-xl border bg-card p-5"><p className="text-sm text-muted-foreground">Savings · {month}</p><p className={`mt-2 text-2xl font-semibold tabular-nums ${totals.savingsCents >= 0 ? "text-emerald-700" : "text-red-700"}`}>{formatCurrency(totals.savingsCents)}</p></div></div>
    {result.items.length ? <div className="space-y-3">{result.items.map((transaction) => <article className="grid gap-3 rounded-xl border bg-card p-4 shadow-sm sm:grid-cols-[7rem_1fr_auto] sm:items-center" key={transaction.id}><div><p className="text-sm font-medium">{transaction.date}</p><p className="flex items-center gap-1.5 text-xs text-muted-foreground">{transaction.accountType ? <AccountTypeIcon accountType={transaction.accountType} className={cn("h-3.5 w-3.5 shrink-0", transaction.accountType === "current" && "text-sky-600", transaction.accountType === "savings" && "text-emerald-600", transaction.accountType === "cash" && "text-amber-600", transaction.accountType === "credit" && "text-violet-600", transaction.accountType === "investment" && "text-rose-600")} /> : <span aria-hidden="true" className="h-3.5 w-3.5 shrink-0 rounded-sm bg-slate-400" />}<span className="truncate">{transaction.accountName}</span></p></div><div className="min-w-0"><h2 className="flex min-w-0 flex-wrap items-baseline gap-x-1.5 font-medium"><span>{transaction.description}</span>{transaction.merchant && <><span aria-hidden="true" className="text-muted-foreground">·</span><span className="max-w-[20ch] truncate text-sm font-normal text-muted-foreground" title={transaction.merchant}>{truncateMerchant(transaction.merchant)}</span></>}</h2><div className="mt-1 flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-muted-foreground"><InlineTransactionControls balanceAction={updateTransactionAccountBalanceAction.bind(null, transaction.id)} categoryControl={transaction.splitCount ? <span>Split across {transaction.splitCount} categories</span> : <InlineCategorySelect action={updateTransactionCategoryAction.bind(null, transaction.id)} categories={options.categories} categoryId={transaction.categoryId} description={transaction.description} />} categoryIsTransfer={options.categories.find((category) => category.id === transaction.categoryId)?.kind === "transfer"} description={transaction.description} excludedFromAccountBalance={transaction.excludedFromAccountBalance} transactionType={transaction.transactionType} typeAction={updateTransactionTypeAction.bind(null, transaction.id)} /></div>{transaction.notes && <p className="mt-1 line-clamp-1 text-xs text-muted-foreground">{transaction.notes}</p>}</div><div className="flex items-center justify-between gap-3 sm:justify-end"><p className={`font-semibold tabular-nums ${transaction.amountCents > 0 ? "text-emerald-700" : ""}`}>{formatCurrency(transaction.amountCents)}</p><Button asChild size="sm" variant="outline"><Link href={`/transactions/${transaction.id}/edit`}>Edit</Link></Button><form action={deleteTransactionAction}><input name="id" type="hidden" value={transaction.id} /><input name="returnQuery" type="hidden" value={returnQuery(params)} /><DeleteTransactionButton /></form></div></article>)}</div>
      : <div className="rounded-xl border border-dashed bg-card p-10 text-center"><h2 className="font-semibold">No matching transactions</h2><p className="mt-2 text-sm text-muted-foreground">Add a transaction or clear the filters to see results.</p>{options.accounts.length ? <Button asChild className="mt-5"><Link href="/transactions/new">Add transaction</Link></Button> : <Button asChild className="mt-5"><Link href="/accounts/new">Add an account first</Link></Button>}</div>}
    <div className="flex flex-col gap-3 text-sm sm:flex-row sm:items-center sm:justify-between"><p className="text-muted-foreground">{result.totalCount} transaction{result.totalCount === 1 ? "" : "s"} · Page {result.page} of {result.totalPages}</p><nav aria-label="Transaction pages" className="flex flex-wrap gap-2"><Button asChild={result.page > 1} disabled={result.page <= 1} size="sm" variant="outline">{result.page > 1 ? <Link href={pageHref(params, 1)}>First</Link> : <span>First</span>}</Button><Button asChild={result.page > 1} disabled={result.page <= 1} size="sm" variant="outline">{result.page > 1 ? <Link href={pageHref(params, result.page - 1)}>Previous</Link> : <span>Previous</span>}</Button><Button asChild={result.page < result.totalPages} disabled={result.page >= result.totalPages} size="sm" variant="outline">{result.page < result.totalPages ? <Link href={pageHref(params, result.page + 1)}>Next</Link> : <span>Next</span>}</Button><Button asChild={result.page < result.totalPages} disabled={result.page >= result.totalPages} size="sm" variant="outline">{result.page < result.totalPages ? <Link href={pageHref(params, result.totalPages)}>Last</Link> : <span>Last</span>}</Button></nav></div>
  </section>;
}
